
services:
  user-service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/user_db
      - USER_SERVICE_URL=http://user-service:8001
      - RESTAURANT_SERVICE_URL=http://restaurant-service:8002
      - DELIVERY_AGENT_SERVICE_URL=http://delivery-service:8003
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - food-delivery-network
    restart: always

  restaurant-service:
    build:
      context: .
      dockerfile: ./restaurant_service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/restaurant_db
      - USER_SERVICE_URL=http://user-service:8001
      - RESTAURANT_SERVICE_URL=http://restaurant-service:8002
      - DELIVERY_AGENT_SERVICE_URL=http://delivery-service:8003
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - food-delivery-network
    restart: always

  delivery-service:
    build:
      context: .
      dockerfile: ./delivery_service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/delivery_db
      - USER_SERVICE_URL=http://user-service:8001
      - RESTAURANT_SERVICE_URL=http://restaurant-service:8002
      - DELIVERY_AGENT_SERVICE_URL=http://delivery-service:8003
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - food-delivery-network
    restart: always

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - food-delivery-network

networks:
  food-delivery-network:
    driver: bridge

volumes:
  postgres_data: