services:
  - type: web
    name: food-delivery-user-service
    env: docker
    plan: free # Explicitly select the free instance type
    dockerContext: .
    dockerfilePath: ./user_service/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: user-db
          property: connectionString
      - key: USER_SERVICE_URL
        value: https://food-delivery-user-service.onrender.com
      - key: RESTAURANT_SERVICE_URL
        value: https://food-delivery-restaurant-service.onrender.com
      - key: DELIVERY_AGENT_SERVICE_URL
        value: https://food-delivery-delivery-service.onrender.com

  - type: web
    name: food-delivery-restaurant-service
    env: docker
    plan: free # Explicitly select the free instance type
    dockerContext: .
    dockerfilePath: ./restaurant_service/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db
          property: connectionString
      - key: USER_SERVICE_URL
        value: https://food-delivery-user-service.onrender.com
      - key: RESTAURANT_SERVICE_URL
        value: https://food-delivery-restaurant-service.onrender.com
      - key: DELIVERY_AGENT_SERVICE_URL
        value: https://food-delivery-delivery-service.onrender.com

  - type: web
    name: food-delivery-delivery-service
    env: docker
    plan: free # Explicitly select the free instance type
    dockerContext: .
    dockerfilePath: ./delivery_service/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: delivery-db
          property: connectionString
      - key: USER_SERVICE_URL
        value: https://food-delivery-user-service.onrender.com
      - key: RESTAURANT_SERVICE_URL
        value: https://food-delivery-restaurant-service.onrender.com
      - key: DELIVERY_AGENT_SERVICE_URL
        value: https://food-delivery-delivery-service.onrender.com

databases:
  - name: user-db
    plan: free
  - name: restaurant-db
    plan: free
  - name: delivery-db
    plan: free