services:
  - type: web
    name: food-delivery-user-service
    env: python
    buildCommand: cd user_service && pip install -r requirements.txt
    startCommand: cd user_service && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: user-db
          property: connectionString
      - key: USER_SERVICE_URL
        value: https://food-delivery-user-service.onrender.com
      - key: RESTAURANT_SERVICE_URL
        value: https://food-delivery-restaurant-service.onrender.com
      - key: DELIVERY_AGENT_SERVICE_URL
        value: https://food-delivery-delivery-service.onrender.com

  - type: web
    name: food-delivery-restaurant-service
    env: python
    buildCommand: cd restaurant_service && pip install -r requirements.txt
    startCommand: cd restaurant_service && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db
          property: connectionString
      - key: USER_SERVICE_URL
        value: https://food-delivery-user-service.onrender.com
      - key: RESTAURANT_SERVICE_URL
        value: https://food-delivery-restaurant-service.onrender.com
      - key: DELIVERY_AGENT_SERVICE_URL
        value: https://food-delivery-delivery-service.onrender.com

  - type: web
    name: food-delivery-delivery-service
    env: python
    buildCommand: cd delivery_service && pip install -r requirements.txt
    startCommand: cd delivery_service && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: delivery-db
          property: connectionString
      - key: USER_SERVICE_URL
        value: https://food-delivery-user-service.onrender.com
      - key: RESTAURANT_SERVICE_URL
        value: https://food-delivery-restaurant-service.onrender.com
      - key: DELIVERY_AGENT_SERVICE_URL
        value: https://food-delivery-delivery-service.onrender.com

databases:
  - name: user-db
    plan: free
  - name: restaurant-db
    plan: free
  - name: delivery-db
    plan: free